version: '3.8'
services:
  ping-server:
    build: .
    ports:
      - "8888:8888"
    environment:
      - BASIC_AUTH_ENABLED=$BASIC_AUTH_ENABLED
      - BASIC_AUTH_USER=$BASIC_AUTH_USER
      - BASIC_AUTH_PASS=$BASIC_AUTH_PASS
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped
